[package]
name = "nw-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
crc32fast = "1.4.2"
regex = "1.10.4"
serde = "1.0.203"
serde_json = { version = "1.0.117" , features = ["preserve_order"] }
walkdir = "2.5.0"
rayon = "1.10.0"
