[package]
name = "file-system"
version = "0.1.0"
edition = "2021"

[dependencies]
pak = { path = "../pak" }
zip = "2.1.0"
walkdir = "2.5.0"
rayon = "1.10.0"
# tokio = { version = "1.37.0", features = ["full"] }
flate2 = "1.0.30"
