[package]
name = "file-system"
version = "0.1.0"
edition = "2021"

[dependencies]
pak = { path = "../pak" }
datasheet = { path = "../datasheet"}
zip = "2.1.1"
walkdir = "2.5.0"
rayon = "1.10.0"
flate2 = "1.0.30"
tokio = { version = "^1.37.0", features = ["full"] }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["async_tokio"] }

[[bench]]
name = "bench"
harness = false
