[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
cliclack = { workspace = true }
dirs = { workspace = true }
regex = { workspace = true }
rusqlite = { workspace = true }
ctrlc = { workspace = true }
