[package]
name = "object-stream"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "^1.9.1"
flate2 = "1.0.30"
crc32fast = "1.4.2"
pelite = "0.10.0"
regex = "1.10.5"
serde = "1.0.203"
serde_json = { version = "1.0.120", features = ["preserve_order"] }
walkdir = "2.5.0"
rayon = "1.10.0"
