[package]
name = "vshapec"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
serde_yml = { workspace = true }
