name: Check

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  
  format:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Format
      run: cargo fmt
      
  check:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Check
      run: cargo check
      
  lint:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Lint
      run: cargo clippy
      
      
  # build:

  #   runs-on: windows-latest

  #   steps:
  #   - uses: actions/checkout@v4
  #   - uses: Swatinem/rust-cache@v2
  #   - name: Build
  #     run: cargo build --release --verbose
  #   # - name: Run tests
  #   #   run: cargo test --verbose
      
