name: Rust

on:
  push:
    branches: [ "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  BINARY_NAME: nwtools-rs

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]
        include:
          - os: windows-latest
            artifact_suffix: .exe
            archive_suffix: -windows.zip
            archive_cmd: 7z a -tzip
          # - os: ubuntu-latest
          #   artifact_suffix: ""
          #   archive_suffix: -linux.tar.gz
          #   archive_cmd: tar czf
          # - os: macos-latest
          #   artifact_suffix: ""
          #   archive_suffix: -macos.tar.gz
          #   archive_cmd: tar czf
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build --release --verbose
    
    - name: Package Binary
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        cd target/release
        ${{ matrix.archive_cmd }} ../../${{ env.BINARY_NAME }}${{ matrix.archive_suffix }} ${{ env.BINARY_NAME }}${{ matrix.artifact_suffix }}
      shell: bash
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ env.BINARY_NAME }}${{ matrix.archive_suffix }}
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
